### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by reconbot** [node-serialport/parsers#2]
Hello and welcome to our roadmap! This issue is a place to suggest and discuss the roadmap for the projects inside this repo.

- [ ] Consider `lerna bootstrap` for npm post install
- [ ] figure out how we get docs or something in each package's readme so their npm pages aren't so unhelpful
- [ ] open a pr to have serialport use these packages and remove code from serialport
- [ ] consider a multi package that has _everything_
